### PR TITLE
fix: history did not handle loading

### LINKED ISSUE #422: adding template does not add to undo stack
breaks undo system if attempt to undo loading template

### PR DESCRIPTION
**Pull request by teykamp**
passes previous state through load
adds the history flag to load options
adds load to history
history correctly tracks load
removes initial load from history

fixes #422

### CODE REVIEW

File: client/src/graphs/plugins/history/types.ts [hunk 1]
```diff
@@ -80,11 +80,36 @@ export type EditRecord = {
   affectedItems: GEdgeLabelEditRecord[];
 };
 
+/**
+ * a record indicating the graph state was loaded
```
Comment (Yonava) [inline client/src/graphs/plugins/history/types.ts:84]: maybe something about how it facilitates both adding and removing nodes and edges in a single record. Loading is the verb we use in base api to describe an action that must require history plugin to have a record for adding and removing in a single record

File: client/src/graphs/plugins/history/types.ts [hunk 2]
```diff
@@ -80,11 +80,36 @@ export type EditRecord = {
...
+ */
+export type LoadRecord = {
+  /**
+   * the action that was taken in order to create this record.
+   */
+  action: 'load';
+  /**
+   * the items that were loaded in.
+   */
+  affectedItems: (GNodeRecord | GEdgeRecord)[];
```
Comment (Yonava) [inline client/src/graphs/plugins/history/types.ts:94]: making this newState or something may be more clear because you are manipulating items in both affectedItems and previousState

Comment (teykamp) [reply client/src/graphs/plugins/history/types.ts:94]: too much work to change the naming convention
